// Datasets page — synthetic X-rays grouped by class (Healthy / Pneumonia / TB).


import { useEffect, useState } from 'react'
import { fetchSyntheticGallery, resolveStorageUrl, downloadSyntheticDatasetZip } from '../api'

// accent styling per class so the three datasets read as distinct
const CLASS_TONE = {
  Healthy: 'text-[#6ee7b7] border-[rgba(52,211,153,0.4)] bg-[rgba(52,211,153,0.06)]',
  Pneumonia: 'text-[#fde047] border-[rgba(250,204,21,0.4)] bg-[rgba(250,204,21,0.06)]',
  Tuberculosis: 'text-[#fca5a5] border-[rgba(248,113,113,0.4)] bg-[rgba(248,113,113,0.06)]',
}

function downloadImage(src, filename) {
  const link = document.createElement('a')
  link.href = src
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
}

function DatasetsPage() {
  const [datasets, setDatasets] = useState([])
  const [selected, setSelected] = useState('Healthy')
  const [loading, setLoading] = useState(true)
  const [err, setErr] = useState(null)
  const [downloading, setDownloading] = useState(false)

  const totalImages = datasets.reduce((sum, d) => sum + (d.count ?? 0), 0)

  // download every generated image across all classes as one ZIP
  async function handleDownloadAll() {
    setErr(null)
    setDownloading(true)
    try {
      const blob = await downloadSyntheticDatasetZip()
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = 'augmed-synthetic-datasets.zip'
      document.body.appendChild(link)
      link.click()
      link.remove()
      URL.revokeObjectURL(url)
    } catch (e) {
      setErr(e instanceof Error ? e.message : 'Dataset download failed.')
    } finally {
      setDownloading(false)
    }
  }

  async function load() {
    setErr(null)
    try {
      const rows = await fetchSyntheticGallery()
      setDatasets(rows)
    } catch (e) {
      setErr(e instanceof Error ? e.message : 'Failed to load datasets.')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load()
  }, [])

  const active = datasets.find((d) => d.class === selected)

  return (
    <div className="bg-slate-900 border border-slate-700 rounded-lg p-6 max-[480px]:p-4">
      <div className="flex items-start justify-between gap-3 flex-wrap mb-1">
        <div>
          <h1 className="text-xl font-bold text-white mb-1">Datasets</h1>
          <p className="text-sm text-slate-400">
            Synthetic chest X-rays generated by the GAN models, grouped by class.
          </p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <button
            type="button"
            onClick={handleDownloadAll}
            disabled={downloading || totalImages === 0}
            className="px-3 py-2 rounded-lg bg-gradient-to-br from-[#5eead4] to-[#60a5fa] text-[#06222a] text-sm font-semibold hover:translate-y-[-1px] transition-transform disabled:opacity-50 disabled:translate-y-0 disabled:cursor-not-allowed"
          >
            {downloading ? 'Zipping…' : `Download all${totalImages ? ` (${totalImages})` : ''}`}
          </button>
          <button
            type="button"
            onClick={() => void load()}
            className="px-3 py-2 rounded-lg border border-slate-700 text-slate-300 text-sm hover:bg-slate-800 hover:text-white"
          >
            Refresh
          </button>
        </div>
      </div>

      {err ? <div className="text-sm text-red-400 mt-3">{err}</div> : null}

      {/* class selector — one card per GAN dataset */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-5">
        {datasets.map((d) => {
          const isActive = d.class === selected
          return (
            <button
              key={d.class}
              type="button"
              onClick={() => setSelected(d.class)}
              className={`text-left rounded-xl border p-4 transition-colors
                ${isActive
                  ? 'border-teal-400/60 bg-teal-400/[0.06]'
                  : 'border-slate-700 bg-slate-800 hover:border-slate-600'}`}
            >
              <div className="flex items-center justify-between gap-2">
                <span className="font-semibold text-white">{d.label}</span>
                <span
                  className={`text-[0.62rem] font-semibold uppercase tracking-wider px-2 py-0.5 rounded-full border whitespace-nowrap
                    ${d.model_available
                      ? 'text-[#6ee7b7] border-[rgba(52,211,153,0.4)] bg-[rgba(52,211,153,0.08)]'
                      : 'text-slate-400 border-slate-600 bg-slate-700/40'}`}
                >
                  {d.model_available ? 'Model ready' : 'Coming soon'}
                </span>
              </div>
              <div className="text-2xl font-bold text-white mt-2">{d.count}</div>
              <div className="text-xs text-slate-400">generated image{d.count === 1 ? '' : 's'}</div>
            </button>
          )
        })}
      </div>

      {/* gallery for the selected class */}
      <div className="mt-6">
        {loading ? (
          <div className="text-center text-slate-400 py-10">Loading datasets…</div>
        ) : !active ? (
          <div className="text-center text-slate-400 py-10 border border-dashed border-slate-700 rounded-lg">
            No dataset selected.
          </div>
        ) : !active.model_available ? (
          <div className="text-center py-12 border border-dashed border-slate-700 rounded-lg">
            <div className={`inline-block text-xs font-semibold uppercase tracking-wider px-3 py-1 rounded-full border mb-3 ${CLASS_TONE[active.class] ?? ''}`}>
              {active.label}
            </div>
            <div className="text-white font-semibold mb-1">Model coming soon</div>
            <p className="text-sm text-slate-400 max-w-md mx-auto">
              The {active.label} GAN isn&apos;t available yet. Once its checkpoint is added,
              generated {active.label.toLowerCase()} X-rays will appear here automatically.
            </p>
          </div>
        ) : active.count === 0 ? (
          <div className="text-center py-12 border border-dashed border-slate-700 rounded-lg">
            <div className="text-white font-semibold mb-1">No {active.label.toLowerCase()} images yet</div>
            <p className="text-sm text-slate-400">
              Head to <span className="text-teal-300">Synthetic Data</span> and generate some — they&apos;ll show up here.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 max-[360px]:grid-cols-1">
            {active.images.map((img) => {
              const src = resolveStorageUrl(img.image_url)
              return (
                <article
                  key={img.id}
                  className="rounded-xl overflow-hidden border border-slate-700 bg-slate-800 flex flex-col"
                >
                  {src ? (
                    <img
                      src={src}
                      alt={`synthetic ${active.label}`}
                      className="w-full aspect-square object-cover bg-black"
                      loading="lazy"
                    />
                  ) : (
                    <div className="w-full aspect-square grid place-items-center text-slate-600 text-xs bg-black/40">
                      X-RAY
                    </div>
                  )}
                  <div className="p-3 flex flex-col gap-2">
                    <span
                      className={`self-start text-[0.62rem] font-semibold uppercase tracking-wider px-2 py-0.5 rounded-full border ${CLASS_TONE[active.class] ?? ''}`}
                    >
                      {active.label}
                    </span>
                    {src ? (
                      <button
                        type="button"
                        onClick={() => downloadImage(src, `${img.id}.png`)}
                        className="w-full px-2 py-1.5 rounded-lg bg-slate-700 text-white text-xs hover:bg-slate-600"
                      >
                        Download
                      </button>
                    ) : null}
                  </div>
                </article>
              )
            })}
          </div>
        )}
      </div>
    </div>
  )
}

export default DatasetsPage
